name = "analytics-petbee"
main = "worker.ts"
compatibility_date = "2026-03-17"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "analytics-db"
database_id = "b7dc0cf8-5096-49f4-927d-a14fb4f0d9ad"
